package setup

import "fmt"

// configAnswers holds everything needed to render a runner config.toml.
type configAnswers struct {
	Region      string
	ImageARN    string
	GitLabURL   string
	Token       string
	BuildsDir   string
	CacheDir    string
	StateDir    string
	MaxDuration int
	InstallPath string
	Concurrent  int
}

// renderConfig produces a ready-to-use GitLab Runner config.toml.
func renderConfig(a configAnswers) string {
	return fmt.Sprintf(`# Generated by `+"`microvm-executor setup`"+`.
concurrent = %d
check_interval = 3

[[runners]]
  name = "aws-lambda-microvm"
  url = "%s"
  token = "%s"
  executor = "custom"
  builds_dir = "%s"
  cache_dir = "%s"
  environment = [
    "MICROVM_REGION=%s",
    "MICROVM_IMAGE_ARN=%s",
    "MICROVM_MAX_DURATION_SECONDS=%d",
    "MICROVM_STATE_DIR=%s",
  ]

  [runners.custom]
    config_exec = "%s"
    config_args = ["config"]
    config_exec_timeout = 60

    prepare_exec = "%s"
    prepare_args = ["prepare"]
    prepare_exec_timeout = 300

    run_exec = "%s"
    run_args = ["run"]

    cleanup_exec = "%s"
    cleanup_args = ["cleanup"]
    cleanup_exec_timeout = 120

    graceful_kill_timeout = 300
    force_kill_timeout = 60
`,
		a.Concurrent, a.GitLabURL, a.Token, a.BuildsDir, a.CacheDir,
		a.Region, a.ImageARN, a.MaxDuration, a.StateDir,
		a.InstallPath, a.InstallPath, a.InstallPath, a.InstallPath,
	)
}

// buildRoleTrust is the trust policy that lets Lambda assume the image build role.
const buildRoleTrust = `{
  "Version": "2012-10-17",
  "Statement": [{
    "Effect": "Allow",
    "Principal": { "Service": "lambda.amazonaws.com" },
    "Action": ["sts:AssumeRole", "sts:TagSession"]
  }]
}`

// buildRolePolicy grants the build role read access to the artifact bucket and
// CloudWatch logs. %s is the bucket name.
const buildRolePolicy = `{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": ["s3:GetObject"],
      "Resource": "arn:aws:s3:::%s/*"
    },
    {
      "Effect": "Allow",
      "Action": ["logs:CreateLogGroup", "logs:CreateLogStream", "logs:PutLogEvents"],
      "Resource": "arn:aws:logs:*:*:*"
    }
  ]
}`
